delete:
  summary: Removes an attendee from exam
  tags:
    - "Exam Attendance"
  security:
    - bearerAuth: []
  parameters:
  - in: path
    name: examId
    required: true
    schema:
      type: string
  - in: path
    name: username
    required: true
    schema:
      type: string
  responses:
    '200':
      description: OK