get:
  summary: Report for user HTML
  tags:
    - "Report"
  security:
    - bearerAuth: []
  parameters:
  - in: query
    name: examId
    required: true
    schema:
      type: string
  - in: query
    name: userId
    required: true
    schema:
      type: string

  responses:
    '200':
      description: report user exam
      content:
        text/plain:
          schema:
            type: string
    '400':
      description: Error
      content:
        application/json:
