get:
  summary: Gets user classes
  tags:
    - "Class"
  security:
    - bearerAuth: []
  responses:
    '200':
      description: Array of class objects in the response
      content:
        application/json:
          schema:
            type: object
            properties:
              classes:
                type: array
                items:
                  $ref: '../../swagger.config.yaml#/components/schemas/classInList'   